# 量化投资 {#qi}

## 股票收益模型

- 股票指数可代表市场，收益率$r_M$
- 某股票跟市场的相关性是市场贝塔（market beta）$\beta_M$
- 市场之外的贡献阿尔法$\alpha$
- 特定股票收益率 $r = \alpha + \beta_M r_M$
- 资本资产定价模型（capital asset pricing model, CAPM）：所有股票阿尔法部分期望是零
- 套利定价理论（arbitrage pricing theory, APT）：除了市场因素，还有其他公用因素来解释股票收益 
- 宏观经济因子模型（macroeconomic factor model, MFM）：$r_i = u_i+\sum_{k=1}^{K}\beta_{ik}f_k$
- 成熟的商业模型可以确定一些共同因素，但也面临不确定性

## 风险

- 单只股票波动很大，一般会组合投资降低风险
- 单只股票波动率$\sigma_i$，两只股票之间的相关系数$\rho_{ij}$，股票组合波动率$\sigma_p^2 = \sum_{i=1}^nw_i^2\sigma_i^2 + \sum_{i\neq j}w_i\sigma_i\rho_{ij}\sigma_jw_j$，其中$w$是股票权重
- 两两间需要估计的参数多
- 因为组合的股票多而共同因素少，可以直接估计与共同因素的相关性来替代总体估计
- 但是除了共同部分还有股票特有特征，所以个股的波动是个体波动与整体波动的综合 $\sigma_i^2 = \sigma_{S,i}^2 + \sum_{l,m = 1,...,K}\beta_{il}\sigma_i\rho_{lm}\sigma_m\beta_{im}$，这里我们认为股票间波动可以用共同波动来解释$\sigma_i\rho_{ij}\sigma_j = \sum_{l,m = 1,...,K}\beta_{il}\sigma_i\rho_{lm}\sigma_m\beta_{im}$
- 所谓风险控制就是通过对每只股票权重的调节优化来降低波动率，但结果不稳定
- 通过风险控制就可以计算收益率，但毕竟有些因素是不可控的，解决的方法就是通过权重调整让其对总收益贡献为零或做空该因素对冲风险
- 风险价值VaR：在某个特定时间段内损失特定金额的概率。一项风险价值为一年5%的总额为1万美元的投资，在一年结束时损失超过1万美元的可能性为5%。简单公式$2M\sqrt{N}$，N次事件中2.5%概率出现M变动的风险价值

## 收益

- 共同因素的收益可通过投资市场指数来获得
- 某特定共同因素的收益需要自己构建，smart beta
- 这属于被动投资，因为股票市场长期看总是上涨，所以收益不差
- 也存在主动投资，根据自己预测投资并不断调整，smart beta属于半被动投资
- 特异收益方面可以进行择时收益（timing skill），但一定注意风控

## 一般性投资

- 三要素：成本、收益、风险
- 时间序列分析：统计学
- 技术分析：根据价格曲线图形进行分析的一种方法，技术分析本质是经验分析，可以量化为模式进行识别，有些指标可以进行机理解释
- 收益的统计分析
        - 环比：以月为周期的相对收益率
        - 同比：以年为周期的相对收益率
        - 收益率一般是正态分布，但也可能是肥尾的，极端事件发生概率高；甚至是长尾，比较极端事件也有可能发生；还有可能出现黑天鹅，非常极端事件
        - 可预见事件会有过度反应然后回调，可进行事件驱动投资
- 影响价格因素的分析，要考虑专业知识、随机性、噪声、数据来源、混杂因素

## 风险管理原理

- 概率论是核心，17世纪出现，保险基础
- 概率乘法规则，每件事都是独立的，联合发生概率是乘积，保险公司认为被保的事相对独立不会同时发生，因为概率特别低
- 二项分布可用来估计准备金比率
- 均值表示集中，几何均值用来估计收益表现，全是正数，比算术均值小
- 方差表示离散
- 风险需要高均值低方差的收益率
- 协方差表示两个变量共同变动的能力
- 相关性是协方差除以各自的标准差
- 回归线截距就是阿尔法，斜率就是贝塔
- 现值就是某物当前的价格，n年后C元的现值是$C/(1+r)^n$，r是利率
- 永续国债每年承诺固定年金C，其现值计算就是个等比数列，等于$C/r$，利率越高国债不值钱，利率低时现值高
- 永续国债也可以承诺每年年金增长，年金现值等于$C/(r-g)$，g是增长利率，一定小于市场利率
- 固定期限年金C付款n年，现值是$C\frac{1-(1/(1+r)^n)}{r}$，利率越高，年限越小，现值越高，贷款买房就是如此，按揭与利率年限有关，年限越长实际现在花的越少，流动性好
- 效用函数U表示钱的边际效果，钱越多，边际效果越低

## 金融技术与发明

- 长期风险，最大的是道德风险（共同利益与个人利益的冲突）
- 经济风险都是可以分担的，消费行为之间是有关联的，社会主义思想下消费行为趋同，通过计划分配来控制分摊风险，但道德风险无法规避
- 框架效应，含义相同但说法不同会导致不同的决策判断
- 公共财政设计税收与福利来控制社会风险，避免道德问题
- 心理账户多是货币框架，但实物框架要考虑消费指数与通胀
- 发明，技术推动金融发展，解决风险问题与框架效应
- 标准化、行政机构、社会保障、邮政服务促进了金融业的发展
- 信用违约交换CDS A借钱给B，但担心B借钱不还，就向C买一份保险，如果B违约，那么C赔付，如果B不违约，那么C净赚。如果B表现很好，那么A可以把买的CDS返卖给C来减少损失，如果表现不好，C也可到期前高价回收CDS来降低风险。这种关系不需要长期维持，可用来交易投机。

## 投资组合

- 高收益低方差组合
- 资产通常不独立
- 寻找预期、标准差、协方差的投资组合，找出有效边界，构成共同基金
- 所有共同基金都试图通过多样化来进行高收益低方差投资并试图打败市场
- 美国股市受益长期高于债券，约4%，发达国家类似，这个现象与政治有关系
- 税收，特别是受益税（企业利润税与个人所得税）对经济有重要调节作用
- 全球范围，企业利润约1/3会被课税（实际税率）
- 投资管理包括资产配置（多样化，占90%）、入场时机与证券选择
- 交易行为本身会对市场产生影响出现系统损耗与负和博弈
- 对冲基金存在生存偏差与回填偏差，多元化可以让投资平稳
- 如果要打败市场，就要主动出击，在多元化保护下平衡风险，吸纳各种来源的非传统投资收益，获取超额收益

## 保险

- 保险与共同基金一样都是通过汇集分摊个体风险管理受益的金融工具，共同基金的受益目标是增值，保险的受益目标是保值与未来损失，个体好恶会导致保险与基金成本不同
- 面对道德风险与选择歧视（只有有风险的买保险）
- 当独立个体风险汇聚一体（二项分布接近正态分布）时，整体风险的期望不变但方差可测算控制
- 合同设计用来标注风险、例外（规避道德风险与选择歧视）、数学模型、公司类型、政府监管（准备金）
- 两种公司，综合险种保险公司与单一险种保险公司，后者风险大、监管严（次贷危机影响）
- 主要类型：财产保险/健康保险/人寿保险
- 寿险保护孩子（遗产），比财险规模大
- 汽车保险收入最高，然后是住房保险
- 始于1600s，金融创新推动
  - 1840s，高薪雇佣保险推销员来推动人们天生的抗拒（农业保险）
  - 1900s，具有现金属性的保险，可升值，但取消后也损失，防止取消保险
  - 19世纪卖给女性丈夫的保险，用宗教转述消除掉道德抵触
- 次贷危机中为债券提供保险的公司购买了大量次贷产品，当评级降低时，出现系统恐慌与抛售，政府举债募资困难，社会衰退
- 气候变化导致的风险是全球性的，也会导致社会衰退，这个风险在提高
- 巨灾债券：没有灾难时发行，有灾难时不偿付或少量偿付，一般是城市发行，用来均摊风险，收益率高与市场相关性低

## 有效市场假说

- 市场价格反映所有有效信息
- 股价反映未来股息价格的现值，否则就是击鼓传花，股息代表盈利能力
- 随机行走理论 $x_t = x_{t-1}+error$
- 一阶自相关回归 因为自相关数据可能回归原点
- Grossman and Stiglitz paradox：如果投资者相信有效市场假说，他们就会停止分析，从而导致市场效率低下；而如果投资者认为市场效率低下，他们就会应用模型进行分析，从而提高市场效率。

## 行为经济学

- 股市是随机运行，现值一直平稳增长
- 期望效用曲线，在预期值附近厌恶损失喜欢收益
- 权重理论，对于确定性的事给更高的权重
- 祝愿性思考，总认为自己心仪的一方会表现好
- 注意力无法长期集中
- 锚定效应，指标锚定
- 赌博行为
- 迷信行为
- 营销手段：吹嘘、隐藏信息、病毒营销与过度交易

## 债券

- 今天的价格*利率=未来的现金流
- 债券是过去的固定利率
- 当前利率提升，债券贬值
- 当前利率下降，债券升值
- 短期折扣债券(bills，低于一年)，低于面值发售
- 中期债券(notes, 一年到十年)，付息
- 长期债券(bonds, 大于十年)，6个月付息一次，老式债券附带利息券，付息时剪下来去银行兑换钱
- 物价指数债券，调整过通胀或CPI的债券，早期指定物品来实现
- 中间商赚取买入卖出价的价差，流动性好的资产价差小，差的或市场小的价差大，卖方主导
- 利率期限结构，不同期限收益率与到期期限的关系
- 利率跟债券价格反向变动

## 银行

- 西方起源于金匠对黄金的保存，采用部分准备金制度进行借贷
- 银行分为商业银行、储蓄银行、存储协会与信用合作社
- 商业银行规模比较大，美国20%的银行资产是外资
- 信用合作社数量比较多，但资产规模小，多为区域内或行业内的
- 存储协会规模中等，数量不多
- 银行解决逆向选择问题，经营核心是关系，对借贷进行筛选
- 银行可以避免企业对债主不道德的资金使用
- 银行提供资金流动性，长贷短存，需要准备金应对挤兑但要保证企业有长期资金
- 发展中国家因为金融体系不健全，银行体系往往规模很大，关系国计民生
- 1988，巴塞尔条约规定银行风险标准
- 里根政府不限制存储协会存款利率，结果风险积聚，最后政府埋单
- 墨西哥政府银行私有化，结果银行过量发放贷款最后全部倒闭，墨西哥银行被海外资本控制
- 亚洲金融危机，外资集中撤资，大量银行倒闭
- 阿根廷银行挤兑风潮
- 美国影子银行发行商业短期借贷票据，银行通过内部组织（SIV）变相担保，但却不接受银行体系监管，出现风险积聚
- 央行是银行的银行，自然发展产物，防止通胀与失业，调节手段主要是准备金率与利率

## 金融监管

- 信息纰漏
- 电话销售促进“锅炉房”交易所的出现
- SEC成立
- 不上市公司无法向公众登广告例如私募对冲基金，但也要接受监管，例如资产达标等
- 局内人与局外人监管，防止内幕信息出现公开时间差
- 会计监管
- SIPC 证券投资保护公司

## 信用评级

- 穆迪评级 1909
- S&P 1916 统计方法评级
- 经营关系
- 接收被评级费用，用制度避免道德风险

## 投行

- 投行是承销证券的机构，不从事对个人的存储与券商业务，主要针对公司票据的发行
- 投行是解决信息不对称的，需要维护较高声誉来担保发行
- 投行可以包销或代销证券
- 预申报阶段，证监会监管发行，严禁公开讨论
- 文件申报静默期，红鲱鱼预招股书披露信息
- 证监会通过后可发行证券
- 通常首次发行也就是IPO时，投行会考虑低价制造高交易量与首日发行价

## 股票

- 公司是法人，要有董事会，公司就是为了盈利存在，向股东负责
- 非盈利公司不发行股票，但也有董事会
- 公司通常会进行股票分割，让股价维持在可买范围（20-40美元），一般一手100股
- 买股票是为了股息，股息董事会决定
- 净值与股票收益比例为PE，一般为15，也就是投资者15年收益回本，收益会计算出来的
- 股息除收益现在都是小于1，说明公司在留钱投资，大于1则出现在大萧条
- 公司可以进行股票回购，与分红本质一样，股利政策不影响价值
- 公司可以举债，提高杠杆率，举债不收税，但债务过高会导致破产成本高
- 林特纳模型认为股息的发放会影响价值与市场反应，股息与盈利间要进行平滑，稳定股息的发放
- 股票买卖要通过经纪人或交易商，前者收取买卖双方佣金，后者自己拥有资产，一个人不能同时是交易商与经纪人
- 交易商与经纪人可以由同一公司管辖，受到监管需要执照
- 股票市场有分级，一级纽交所，二级纳斯达克，三级市场小盘股粉单，四级市场大宗交易
- 交易是技术推动的，从纸到复写纸、打印机、电报、自动收录机，跨市场交易系统
- 纽交所曾经允许租用股票，大萧条后禁止
- 交易单分为市场订单与限制订单，前者按当前价格成交，后者除了数量还要求价格
- 目前交易是网上公开订单了
- 股票市场成立基础是人人平等与限制负债
- 股市存在羊群效应，散户追随机构大单，惧买是想等卖出大单进一步下跌再买，惜售是等大单进一步上涨再卖
- Gopikrishnan等人发现从5分钟到120分钟的美股个股和指数的尾部都服从幂律形式，其正尾标度指数略大于负尾标度指数，但都接近于3
- 在中国股市中，惧买效应要大于惜售效应。
- 在中国股市中，不同市场时期的惧买与惜售效应的强度是不一样的：牛熊时期的惧买与惜售效应要大于震荡时期的惧买与惜售效应。
- 聪明钱交易，设计聪明系数Q，前20%聪明交易量占总交易量的比例，越高说明悲观逢高出货，越低说明乐观逢低吸筹，按Q排序，选最小的持有一个月卖出，聪明交易用惜售来表示

## 房产

- 美国房产规模与股票接近
- 房地产存在DPP，有限合伙制，可避税
- 商业房地产公司 REITS 限制很多
- 商业用房也可算资产，但不算地产公司
- 贷款价值比不能超过1
- 最早房产贷款期限很短，只有5年，贷款价值比不超过60%，但只还利息，最后还本金，续约时如果房产贬值就会收回房子
- 美国出台房屋贷款公司，提供15年贷款，但本息一起还
- 后来贷款进一步延长到30年，但因为考虑退休后收入下降，一般不超过30年
- 后来出现面向低收入者的2+28浮动利率贷款，但后面利率很高
- 房贷按揭固定还款最开始还的是利息，越往后本金比例越高，公式等同年金计算公式
- 房地产业存在全球尺度的非理性繁荣

## 期货

- 起源于日本农产品交易，每日交易结束会有导火线与泼水活动
- 最开始是现货交易，之后出现远期合约，约定货币交割的地点与日期的合同
- 期货跟远期合约的最大区别在于货品进行了标准化处理，这样交易流动性提高
- 期货价格的公允价格等于现货价格乘以一加到期利率与存储成本或其他成本
- 股指期货对标股票指数的期货，价格等于远期价格乘以现在价格在利率与分红调整的数，如果利率等于分红，那么期货与现价几乎一样，市场规模与股票类似
- 石油期货里存储成本很高
- 房地产指数期货

## 期权

- 包含行权日与行权价格 call 看涨 put 看跌
- 美式期权与欧式期权，后者只讨论行权日价格
- 1973 芝加哥首个期权交易所 CBOE
- 期货也有期权
- 股票与期权组合可以无风险套利
- Black-Scholes 公式
- 可作为风险管理工具

## 金融民主化

- 政府是社会风险管理者，金融要提供工具
- 道德与职业化
- 行为经济学中普通人是弱势方
- 工资退税
- 德国 1883 全民社保
- 美国照搬德国，社会保险是个人企业配比的
- 破产法允许个人破产，比离婚比率高
- 小额贷款银行与慈善



